package exceptions

import (
	"testing"
)

func TestErrorWrap(t *testing.T) {
}
